name: starter

services:
  - name: couchbase
    image: jeremiahchienda/oaf-couchbase-starter:latest
    bindings:
      - port: 11210
        name: data
        connectionString: http://${host}:${port}
      - port: 8091
        name: ui
      - port: 8092
        name: indexing
      - port: 8093
        name: query
      - port: 8094
        name: search
  - name: api
    project: src/Api/Api.csproj
    bindings:
      - port: 5000
  - name: worldConsumer
    project: src/WorldConsumer/WorldConsumer.csproj
    bindings:
      - port: 3000